events {}

http {

    upstream api_a1a {
        server qc_api_a1a:5008;
    }

    upstream api_tac {
        server qc_api_tac:5008;
    }

    server {
        listen 80;

        location /api-a1a/ {
            proxy_pass http://api_a1a/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api-tac/ {
            proxy_pass http://api_tac/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}